"""Add job_search_limit to preferences

Revision ID: 3705d7e21388
Revises: 
Create Date: 2025-09-05 17:03:48.165134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3705d7e21388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_search_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.drop_column('job_search_limit')

    # ### end Alembic commands ###
