"""Add experience_level column

Revision ID: bf7953bebe6a
Revises: d5ff0cc96892
Create Date: 2025-09-18 08:42:44.448843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7953bebe6a'
down_revision = 'd5ff0cc96892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.drop_column('experience_level')

    # ### end Alembic commands ###
