"""Remove daily_application_limit field from preferences

Revision ID: c9136e9f1c19
Revises: 3705d7e21388
Create Date: 2025-09-09 09:38:34.434723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9136e9f1c19'
down_revision = '3705d7e21388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.drop_column('daily_application_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_application_limit', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
