"""Add status_changed_date and recruiter_notes fields

Revision ID: d5ff0cc96892
Revises: e8d8ca1678f8
Create Date: 2025-09-10 08:45:11.813997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ff0cc96892'
down_revision = 'e8d8ca1678f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_changed_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recruiter_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('recruiter_notes')
        batch_op.drop_column('status_changed_date')

    # ### end Alembic commands ###
