"""Add job_boards column to preferences

Revision ID: e6e3506cfcb2
Revises: bf7953bebe6a
Create Date: 2025-09-18 09:03:31.943382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e3506cfcb2'
down_revision = 'bf7953bebe6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_boards', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.drop_column('job_boards')

    # ### end Alembic commands ###
