"""Add has_easy_apply field to job_postings

Revision ID: e8d8ca1678f8
Revises: c9136e9f1c19
Create Date: 2025-09-10 07:51:28.942124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d8ca1678f8'
down_revision = 'c9136e9f1c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_easy_apply', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('has_easy_apply')

    # ### end Alembic commands ###
